import {StyleSheet} from 'react-native'

const style = StyleSheet.create({
    navbar:{
        flex:1
    },
    container:{
        flex:1 ,
        backgroundColor:"#F3F3F3",
        flexDirection:'column', 
        paddingRight:50
    },
    imagegiant:{
        flex:1
    },
    home:{
        flex:1, 
        flexDirection:'column', 
        paddingTop:'1%', 
        paddingLeft:40
    },
    containertext:{
        alignItems:'center'
    },
    title:{
        fontSize:30,
        fontWeight:'bold',
        color:'#3E6097',
        textAlign:'center',
        paddingTop:20
    },
    description:{
        fontSize:18,
        color:'#374754',
        textAlign:'center'
    },
    containersearch:{
        backgroundColor:'#E3E1E1',
        width:'100%',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    searchbar:{
        padding:10,
        alignItems:'flex-end',
        paddingRight:25,
    },
    table:{
        flex:1,
    },
    containerimage:{
        height:'80%',
    },
    image:{
        flex:1,
        width: '90%',
        borderRadius:20
    },
    cardscontainer:{
        justifyContent:'flex-end',
        alignItems:'flex-end',
        flexDirection:'row'
    },
    cards:{
        backgroundColor:'#C7C7C7',
        padding:10,
        borderTopRightRadius:20,
        borderTopLeftRadius:20,
        paddingLeft:10,
        maxWidth:300,
        minWidth:150,
        borderColor:'#E3E1E1',
        borderWidth:1
    },
    cardsAdd:{
        backgroundColor:'#3E6097',
        padding:10,
        borderTopRightRadius:20,
        borderTopLeftRadius:20,
        paddingLeft:10,
        maxWidth:300,
        minWidth:150,
        borderColor:'#E3E1E1',
        borderWidth:1
    },
    addmusic:{
        fontSize:18,
        color:'white',
        textAlign:'center'
    },
    removemusic:{
        fontSize:18,
        color:'#760000',
        textAlign:'center'
    },
    nameartist:{
        fontSize:30,
        paddingLeft:10,
        textAlign:'center',
        color:'#374754',
        fontWeight:'bold'
    },
    playlistdescription:{
        backgroundColor:'#E3E1E1',
        paddingRight:10,
        paddingLeft:10
    },
    imageartist:{
        flex:1,
        justifyContent:'center',
        backgroundColor:'#E3E1E1',
        justifyContent:'center',
        alignItems:'center',
        paddingTop:20,
        paddingBottom:50
    }
});

export default style